### ISSUE TITLE
[Bug]: Teleporting creates obsidian spawn pad in End

### ISSUE THREAD

**Issue by rckymtnrfc** [terrarium-earth/Tempad#60] opened 2023-08-21 17:01 UTC
### Bug Description

Minecraft 1.19.2
Forge 43.2.18
Tempad 1.4.5

When I create a location in the End and later teleport to that location, it creates a obsidian spawn pad in that location (it also creates air blocks above the spawn pad).  I'm assuming it's triggering a vanilla feature because it's the same spawn pad that is created the first time you go to the End.

I thought it was due to the fact that my ender farm is located at the bottom of the void but I also tested it on the center End island (y level 52) as well as one of the outer islands (y level 62) and got the same obsidian spawn pad.

### How to Reproduce?

Create Location in The End
Teleport to said location.

### Expected Behavior

Not replacing existing blocks.

### Version

1.4.5

### Mod Loader Version

Forge 43.2.18

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Ulysses2** [comment] 2023-11-10 13:38
Looks like the issue is in TempadTeleporter class which needs to override placeEntity to apply with false instead of true. At least that's what the code looks like to me but I haven't tested it myself.

**Comment by CodexAdrian** [comment] 2023-11-26 16:53
Fixed in dev

**Closed as completed by CodexAdrian** 2023-11-26 16:53 UTC
Labels: bug
