### ISSUE TITLE
[Bug]: Can still teleport when there's not enough fuel in Forge for Minecraft 1.20.1

### ISSUE THREAD

**Issue by MadCatterDev** [terrarium-earth/Tempad#97] opened 2024-02-15 17:21 UTC
### Bug Description

I can still teleport (in survival mode) when I don't have enough fuel to teleport. I tested it with the timer and experience levels.

### How to Reproduce?

Try to teleport.

### Expected Behavior

The teleport button should be disabled.

### Version

2.3.3

### Mod Loader Version

1.20.1 - 47.2.17

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment] 2024-02-15 17:23
Are you sure you dont have another tempad in your inventory that is able to teleport you? If you have 2 tempads in your inventory, if one is on cooldown, itll go to the next one not on cooldown when you go to open it. Can you also send the configs you used?

**Comment by MadCatterDev** [comment] 2024-02-15 17:37
Oh, I didn't know that was a thing.

[tempad-client.jsonc](https://github.com/terrarium-earth/Tempad/files/14300411/tempad-client.jsonc)
[tempad.jsonc](https://github.com/terrarium-earth/Tempad/files/14300412/tempad.jsonc)

**Comment by MadCatterDev** [comment] 2024-02-15 17:40
I think it shouldn't fallback to using a different tempad, or that behavior should be configurable.

**Comment by CodexAdrian** [comment] 2024-02-15 17:42
The tempad is intended to be used as a single unit, not with multiple in your inventory. Thats why the locations are all serverside. The fallback is an unintended side effect of the Tempad being able to operate out of any slot in your inventory.

**Comment by CodexAdrian** [comment] 2024-02-28 23:08
Duplicate of #97

**Comment by CodexAdrian** [comment] 2024-02-28 23:10
im dumb

**Comment by CodexAdrian** [comment] 2024-07-02 01:57
Fixed in 1.21

**Closed as completed by CodexAdrian** 2024-07-02 01:57 UTC
Labels: bug
