### ISSUE TITLE
[Bug]: Fails to Render Timegate while using a shader 

### ISSUE THREAD

**Issue by ZyriBlackwood** [terrarium-earth/Tempad#104] opened 2024-03-01 02:30 UTC
### Bug Description

The Teleport gate is rendered invisible when used with "Complementary Shaders."

[Complementary Shaders](https://www.complementary.dev/shaders/)

I am using it on fabric

fabric API. 0.94.4
Fabric loader version: 0.15.7

### How to Reproduce?

1. Have Complementary shaders installed.
2. Have all Shader settings set to the highest values
3. Using unbound version
4. Aquire Tempad.
5. Save the teleport location
6. Attempt to teleport to location.

### Expected Behavior

To see the gate.

### Version

2.3.7

### Mod Loader Version

fabric 0.15.07

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment] 2024-03-01 02:31
Duplicate of #48

**Closed as not planned by CodexAdrian** 2024-03-01 02:31 UTC
Labels: bug
