### ISSUE TITLE
[Bug]: portal doesnt show with shaders

### ISSUE THREAD

**Issue by seavord** [terrarium-earth/Tempad#126] opened 2024-11-24 01:41 UTC
### Bug Description

 portal doesnt show with shaders

### How to Reproduce?

press k and go off shaders and you will see it press k again and its gone

im using the complementary shaders

### Expected Behavior

to see the portal in shaders 

### Version

1.20.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment] 2024-11-24 01:42
Duplicate of #51

**Closed as completed by CodexAdrian** 2024-11-24 01:42 UTC
Labels: bug
